# --- General Env ---
env_name: "HalfCheetah-v5"
env_is_atari: false
env_is_mujoco: true
n_stack: 0

# --- Training Parameters ---
train:
  random_seed: 42
  algo: "PPO"
  run_id: "1" # for tensorboard logging
  policy: "default" # either "own" or "default"
  n_envs: 1 # Recommended for Mujoco
  n_steps: 2048 # Following the 37 implementation details of Proximal Policy Optimization
  batch_size: 512 # They say batch size nminibatches = 32 so 1 x 2048 / 32 = 64
  n_opt_epochs: 10 
  total_timesteps: 1000000
  ent_coef: 0.00 # Again following the 37 implementation details of Proximal Policy Optimization for mujoco
  decay_lr_init: 3e-4 # And same again
  decay_lr_final_frac: 0.3 
  clip_epsilon: 0.1
  force_cpu: false

# --- Logging & Saving ---
logging:
  log_dir: "./logs_halfcheetah/"
  name_prefix: "ppo1_halfcheetah_latest"
  checkpoint_save_freq: 10000 # OverwriteCheckpointCallback save frequency

# --- Visualization ---
visualize:
  video_folder: "videos_halfcheetah/"
  deterministic: true
